appratoo_platform:
    resource: "@AppratooPlatformBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_registration_confirmed:
    path: /
    defaults: { _controller: AppratooPlatformBundle:Home:index }
